---
title: "Mayors"
author: "Maria Burzillo"
date: "4/18/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(readr)
library(tidyverse)
```


```{r import data, include = FALSE}

mayors <- read_csv("mayor_data.csv")

# take only basic vars needed
simple_mayor <- mayors %>%
  select(city, cityid, year, citystabbr, winnername, winnerparty, incumbentpercent, incumbentlose, 
         incumbentwin, losername, winnerrace, winnerpercent, loserparty, loserpercent, 
         countyname, loserrace, diffwinnerandloser) %>%
  filter(!(is.na(winnerrace))) %>%
  mutate(source = "HopkinsPettingill", cityst = citystabbr)%>%
  separate(citystabbr, into = c("city1", "stateab"), sep = -2) %>%
  select(-city1)

threshold_cities <- read_csv("threshold_merge.csv")

# large file -> should subset and save again
fin_seg <- read_csv("fin_seg.csv")

fin_seg %>%
  select(name00) %>%
  unique() %>%
  view()

simple_mayor %>%
  select(city, stateab) %>%
  unique() %>%
  view()

write.csv(simple_mayor, "Hopkins_Pettingill_mayors.csv")

```


```{r create surveying indicators, include = FALSE}
simple_mayor <- simple_mayor %>%
  mutate(holc_city = NA) 

simple_mayor$holc_city[simple_mayor$citystabbr == "AuroraIL"] <- "Aurora"
simple_mayor$holc_city[simple_mayor$citystabbr == "BeaumontTX"] <- "Beaumont"
simple_mayor$holc_city[simple_mayor$citystabbr == "Colorado SpringsCO"] <- "Colorado Springs"
simple_mayor$holc_city[simple_mayor$citystabbr == "ColumbiaSC"] <- "Columbia"
simple_mayor$holc_city[simple_mayor$citystabbr == "ColumbusGA"] <- "Columbus"
simple_mayor$holc_city[simple_mayor$citystabbr == "Corpus ChristiTX"] <- "Corpus Christi"
simple_mayor$holc_city[simple_mayor$citystabbr == "DurhamNC"] <- "Durham"
simple_mayor$holc_city[simple_mayor$citystabbr == "FresnoCA"] <- "Fresno"
simple_mayor$holc_city[simple_mayor$citystabbr == "GalvestonTX"] <- "Galveston"
simple_mayor$holc_city[simple_mayor$citystabbr == "GreensboroNC"] <- "Greensboro"
simple_mayor$holc_city[simple_mayor$citystabbr == "GreenvilleSC"] <- "Greenville"
simple_mayor$holc_city[simple_mayor$citystabbr == "High PointNC"] <- "High Point"
simple_mayor$holc_city[simple_mayor$citystabbr == "JolietIL"] <- "Joliet"
simple_mayor$holc_city[simple_mayor$citystabbr == "LaredoTX"] <- "Laredo"
simple_mayor$holc_city[simple_mayor$citystabbr == "LexingtonKY"] <- "Lexington"
simple_mayor$holc_city[simple_mayor$citystabbr == "LubbockTX"] <- "Lubbock"
simple_mayor$holc_city[simple_mayor$citystabbr == "MaconGA"] <- "Macon"
simple_mayor$holc_city[simple_mayor$citystabbr == "MadisonWI"] <- "Madison"
simple_mayor$holc_city[simple_mayor$citystabbr == "MonroeLA"] <- "Monroe"
simple_mayor$holc_city[simple_mayor$citystabbr == "OrlandoFL"] <- "Orlando"
simple_mayor$holc_city[simple_mayor$citystabbr == "PhoenixAZ"] <- "Phoenix"
simple_mayor$holc_city[simple_mayor$citystabbr == "RaleighNC"] <- "Raleigh"
simple_mayor$holc_city[simple_mayor$citystabbr == "San JoseCA"] <- "San Jose"
simple_mayor$holc_city[simple_mayor$citystabbr == "TucsonAZ"] <- "Tucson"

#simple_mayor %>% filter(citystabbr == "AuroraIL")

simple_mayor %>%
  filter(!(is.na(holc_city)), winnerrace != "white", winnerrace != ".")

## going to need to supplement with additional data...

colnames(simple_mayor)
```


```{r create surveying indicators, include = FALSE}
# merge with threshold dataset

simple_mayor_holc <- simple_mayor %>%
  filter(!(is.na(holc_city)))

threshold_cities_merged <- left_join(simple_mayor, threshold_cities, by = c("city" = "City", "stateab" = "State")) 

threshold_cities_merged <- threshold_cities_merged%>% 
  filter(!(is.na(Surveyed)), winnerrace != ".")  %>%
  mutate(winner_black = ifelse(winnerrace == "black", 1, 0))

threshold_cities_merged %>%
  ggplot(aes(x = winner_black)) +
  geom_bar() +
  facet_wrap(~Surveyed)

threshold_cities_merged %>%
  ggplot(aes(x = year, y = winner_black)) +
  geom_point() +
  geom_smooth(se = F) +
  facet_wrap(~Surveyed)

write.csv(threshold_cities_merged, "threshold_cities_merged.csv")

```


```{r data supplement from https://blackdemographics.com/culture/black-politics/black-mayors/}

black_demo <- tibble(
  "holc_city" = c(NA),
  "stateabbr" = c(NA),
  "year" = c(NA), 
  "citystabbr" = c(NA), 
  "winnerrace" = c(NA),
  "winnername" = c(NA),
  "source" = "blackdemo"           
)

        
new <- load("/Users/mariaburzillo/Downloads/mayors_rdd_analysis_final.RData")

new1 <- load("/Users/mariaburzillo/Downloads/place_demog.RData")
```

