---
title: "Mayors full sample"
author: "Maria Burzillo"
date: "4/23/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(readr)
library(stringr)
```

```{r import data}
# mayor data
vogl_mayor <- read.csv("mayors_share_vogl.csv")
hp_mayors <- read.csv("Hopkins_Pettingill_mayors.csv")

# get cities within 10k range
cities_1930 <- read.csv("ipums_1930_cities_by_pop_full_sample.csv") %>%
  select(city_code = city, cityname, state, citypop_total)

# cities within 20-60 range
cities_1930_20_60 <- cities_1930 %>%
  filter(citypop_total <= 60000,
         citypop_total >= 20000) %>%
  mutate(surveyed = ifelse(citypop_total >= 40000, 1, 0)) 

```


```{r clean vogl data}

vogl_mayor_clean <- vogl_mayor %>%
  rename(raw_city = city, raw_state = state) %>%
  separate(name, c("cityname", "state"),",") %>%
  separate(state, c("space", "state"), " ") %>%
  #select(-space, -raw_city, -raw_state) %>%
  mutate(cityname = as.character(str_to_title(cityname)), vogl = 1) %>%
  select(cityname, state, year, bmayor, vogl)

vogl_mayor_clean$cityname[vogl_mayor_clean$cityname == "Lexington-Fayette" & vogl_mayor_clean$state == "KY"] <- "Lexington"

vogl_mayor_clean %>%
  filter(is.na(bmayor))

vogl_mayor_clean %>%
  filter(cityname == "Lexington")
```



```{r clean Hopkins Pettingill data, include = FALSE}

# first join for cities not present in the other data -> no worry about overlap of city-years

missing_cities <- c("DanvilleVA", "KankakeeIL", "La GrangeGA", "MaywoodIL",
                    "MeridianMS", "NewburghNY", "Pine BluffAR", "PoughkeepsieNY",
                    "Rocky MountNC", "RomeGA", "SpartanburgSC", "WilmingtonNC")

#duplicate_but_missing_cities <- c("Colorado SpringsCO","DurhamNC", "FresnoCA", "RaleighNC", "TucsonAZ", "West Palm BeachFL", "BeaumontTX", "PensacolaFL","GreenvilleSC")

# missing_all <- c(missing_cities, duplicate_but_missing_cities)

# hp_mayors %>% filter(cityst == "WilmingtonNC")

other_race = c("asian", "hispanic", "white")

hp_mayors_sub <- hp_mayors %>%
  filter(cityst %in% missing_cities) %>%
  mutate(bmayor = ifelse(winnerrace == "black", 1, ifelse(winnerrace %in% other_race, 0, NA))) %>%
  mutate(bmayor_to_sum = ifelse(winnerrace == "black", 1,  0)) %>%
  group_by(cityst) %>%
  mutate(tot_bmayor = sum(bmayor_to_sum, na.rm = T)) %>%
  ungroup() %>%
  mutate(bever = ifelse(tot_bmayor > 0, 1, 0))

# hp_mayors_sub %>% select(winnerrace, bmayor)

# unique(hp_mayors$winnerrace)

hp_mayors_clean <- hp_mayors %>%
  mutate(bmayor = ifelse(winnerrace == "black", 1, ifelse(winnerrace %in% other_race, 0, NA))) %>%
  mutate(bmayor_to_sum = ifelse(winnerrace == "black", 1,  0)) %>%
  group_by(cityst) %>%
  mutate(tot_bmayor = sum(bmayor_to_sum, na.rm = T)) %>%
  ungroup() %>%
  mutate(bever = ifelse(tot_bmayor > 0, 1, 0), hp = 1) %>%
  select(city, stateab, year, bmayor,  hp, winnername) %>%
  filter(!(is.na(bmayor)))

hp_mayors_clean %>%
  filter(city == "Albany", stateab == "GA")

vogl_mayor %>%
  filter(name == "ALBANY, GA")

```


```{r initial join and dealing with year, state, city, race mismatches}

# join -> deal with the matches -> don't want any matches!! other than that should be good :)
full_unfiltered <- full_join(vogl_mayor_clean, hp_mayors_clean, by = c("cityname" = "city", "state" = "stateab", "year" = "year", "bmayor" = "bmayor")) %>%
  mutate(match = ifelse(vogl == 1 & hp == 1, 1, 0))

# are there any observations where the mayor status does not match?

full_unfiltered %>%
  mutate(count = 1) %>%
  group_by(cityname, state, year) %>%
  summarise(tot_count = sum(count)) %>%
  filter(tot_count != 1)


# there are cases where the data conflicts on race of mayor... checking and fixing
vogl_mayor_clean$bmayor[(vogl_mayor_clean$cityname == "Albany" & vogl_mayor_clean$state == "GA" & vogl_mayor_clean$year == 2004)] <- 1

vogl_mayor_clean$bmayor[(vogl_mayor_clean$cityname == "Alexandria" & vogl_mayor_clean$state == "VA" & vogl_mayor_clean$year == 2003)] <- 1
vogl_mayor_clean$bmayor[(vogl_mayor_clean$cityname == "Alexandria" & vogl_mayor_clean$state == "VA" & vogl_mayor_clean$year == 2006)] <- 1
vogl_mayor_clean$bmayor[(vogl_mayor_clean$cityname == "Alexandria" & vogl_mayor_clean$state == "VA" & vogl_mayor_clean$year == 2009)] <- 1

vogl_mayor_clean$bmayor[(vogl_mayor_clean$cityname == "Atlantic City" & vogl_mayor_clean$state == "NJ" & vogl_mayor_clean$year == 1990)] <- 0

vogl_mayor_clean$bmayor[(vogl_mayor_clean$cityname == "Beaumont" & vogl_mayor_clean$state == "TX" & vogl_mayor_clean$year == 2002)] <- 0

vogl_mayor_clean$bmayor[(vogl_mayor_clean$cityname == "Camden" & vogl_mayor_clean$state == "NJ" & vogl_mayor_clean$year == 1997)] <- 0

vogl_mayor_clean$bmayor[(vogl_mayor_clean$cityname == "Chesapeake" & vogl_mayor_clean$state == "VA" & vogl_mayor_clean$year == 1992)] <- 1
vogl_mayor_clean$bmayor[(vogl_mayor_clean$cityname == "Chesapeake" & vogl_mayor_clean$state == "VA" & vogl_mayor_clean$year == 1996)] <- 1
vogl_mayor_clean$bmayor[(vogl_mayor_clean$cityname == "Chesapeake" & vogl_mayor_clean$state == "VA" & vogl_mayor_clean$year == 2000)] <- 1

vogl_mayor_clean$bmayor[(vogl_mayor_clean$cityname == "Chester" & vogl_mayor_clean$state == "PA" & vogl_mayor_clean$year == 2003)] <- 1


vogl_mayor_clean$bmayor[(vogl_mayor_clean$cityname == "Cincinnati" & vogl_mayor_clean$state == "OH" & vogl_mayor_clean$year == 1991)] <- 1
vogl_mayor_clean$bmayor[(vogl_mayor_clean$cityname == "Cincinnati" & vogl_mayor_clean$state == "OH" & vogl_mayor_clean$year == 1993)] <- 0
vogl_mayor_clean$bmayor[(vogl_mayor_clean$cityname == "Cincinnati" & vogl_mayor_clean$state == "OH" & vogl_mayor_clean$year == 2005)] <- 1

vogl_mayor_clean$bmayor[(vogl_mayor_clean$cityname == "Cleveland" & vogl_mayor_clean$state == "OH" & vogl_mayor_clean$year == 1989)] <- 1
vogl_mayor_clean$bmayor[(vogl_mayor_clean$cityname == "Cleveland" & vogl_mayor_clean$state == "OH" & vogl_mayor_clean$year == 2001)] <- 0

vogl_mayor_clean$bmayor[(vogl_mayor_clean$cityname == "Columbus" & vogl_mayor_clean$state == "OH" & vogl_mayor_clean$year == 1999)] <- 1

vogl_mayor_clean$bmayor[(vogl_mayor_clean$cityname == "Dallas" & vogl_mayor_clean$state == "TX" & vogl_mayor_clean$year == 2002)] <- 0

vogl_mayor_clean$bmayor[(vogl_mayor_clean$cityname == "Dayton" & vogl_mayor_clean$state == "OH" & vogl_mayor_clean$year == 1993)] <- 0
vogl_mayor_clean$bmayor[(vogl_mayor_clean$cityname == "Dayton" & vogl_mayor_clean$state == "OH" & vogl_mayor_clean$year == 2001)] <- 1

vogl_mayor_clean$bmayor[(vogl_mayor_clean$cityname == "Denver" & vogl_mayor_clean$state == "CO" & vogl_mayor_clean$year == 2003)] <- 0

vogl_mayor_clean$bmayor[(vogl_mayor_clean$cityname == "Des Moines" & vogl_mayor_clean$state == "IA" & vogl_mayor_clean$year == 1997)] <- 1
vogl_mayor_clean$bmayor[(vogl_mayor_clean$cityname == "Des Moines" & vogl_mayor_clean$state == "IA" & vogl_mayor_clean$year == 1999)] <- 1

vogl_mayor_clean$bmayor[(vogl_mayor_clean$cityname == "Durham" & vogl_mayor_clean$state == "NC" & vogl_mayor_clean$year == 1991)] <- 0

vogl_mayor_clean$bmayor[(vogl_mayor_clean$cityname == "Gary" & vogl_mayor_clean$state == "IN" & vogl_mayor_clean$year == 1995)] <- 0

vogl_mayor_clean$bmayor[(vogl_mayor_clean$cityname == "Greensboro" & vogl_mayor_clean$state == "NC" & vogl_mayor_clean$year == 2007)] <- 1

vogl_mayor_clean$bmayor[(vogl_mayor_clean$cityname == "Hampton" & vogl_mayor_clean$state == "VA" & vogl_mayor_clean$year == 2004)] <- 0

vogl_mayor_clean$bmayor[(vogl_mayor_clean$cityname == "Hartford" & vogl_mayor_clean$state == "CT" & vogl_mayor_clean$year == 1993)] <- 0


# there are 595 full matches -> get rid of these in hp data
to_remove_from_hp <- full_unfiltered %>%
  filter(match == 1) %>%
  select(city =, stateab =, year =)


full_unfiltered %>%
  filter(cityname == "Lexington", state == "CA", year == "1965")

vogl_mayor_clean %>%
  filter(cityname == "Lexington", state == "CA", year == "1965")

vogl_mayor %>%
  filter(name == "CINCINNATI, OH", year == 1993)

hp_mayors %>%
  filter(city == "Cincinnati", stateab == "OH", year == 1993)


# join -> deal with the matches -> don't want any matches!! other than that should be good :)
full_unfiltered <- full_join(vogl_mayor_clean, hp_mayors_clean, by = c("cityname" = "city", "state" = "stateab", "year" = "year", "bmayor" = "bmayor")) %>%
  mutate(match = ifelse(vogl == 1 & hp == 1, 1, 0))

# are there any observations where the mayor status does not match?

full_unfiltered %>%
  mutate(count = 1) %>%
  group_by(cityname, state, year) %>%
  summarise(tot_count = sum(count)) %>%
  filter(tot_count != 1)

full_unfiltered %>%
  filter(cityname == "Hartford", state == "CT", year == 1993)
```











```{r examining duplicates -> NONE SHOULD BE ADDED, include = FALSE}

# figure out the doubles
duplicate_cities <- c("AmarilloTX", "AuroraIL", "ChesterPA", 
                      "ColumbiaSC", "ColumbusGA", "Corpus ChristiTX", 
                      "GalvestonTX", "GreensboroNC", "JacksonMS", "JolietIL",
                      "LaredoTX", "LubbockTX", "MaconGA", "MadisonWI", 
                      "MonroeLA", "OrlandoFL",
                      "PhoenixAZ",  "San JoseCA", "Sioux FallsSD",
                      "StocktonCA")

length(duplicate_cities)

# do the duplicate cities also have duplicate years? -> 84 potential duplicates
hp_mayors_duplicate_sub <- hp_mayors %>%
  filter(cityst %in% duplicate_cities) %>%
  select(city,stateab, year, source)


hp_mayors_sub <- hp_mayors %>%
  select(cityname = city, state = stateab, year)

# %>% mutate(source = "hp")

vogl_mayor_clean_sub <- vogl_mayor_clean %>%
  select(cityname, state, year) %>% mutate(source = "vogl")

city_state_matches <- left_join(hp_mayors_duplicate_sub, vogl_mayor_clean_sub, by = c("city" = "cityname", "stateab" = "state"))

city_state_matches <- left_join(hp_mayors_sub, vogl_mayor_clean_sub)



# for year duplicates, want to know if ones already in vogl also in new
city_state_year_matches <- left_join(vogl_mayor_clean_sub, hp_mayors_duplicate_sub, by = c("cityname" = "city", "state" = "stateab", "year" = "year")) 

# not matched from vogl -> These don't appear to be in Vogl at all... why marked in originally?
city_state_matches %>%
  filter(is.na(good))

# match with hp by year, city, state -> need to remove from that before joining to avoid duplicates -> all potential duplicates are matched -> need to remove all
city_state_year_matches %>%
  filter(source == "HopkinsPettingill")

hp_mayors_sub

city_state_matches %>%
  mutate(count = 1) %>%
  filter(source == "vogl") %>%
  group_by(cityname, state) %>%
  summarise(tot_count = sum(count))

```


```{r}

```


```{r join both sources of mayor data, include = FALSE}
# 14214 obs (11,224)
vogl_mayor_clean %>%
  mutate(count = 1) %>%
  #filter(year == 2002 | year == 2007) %>%
  filter(cityname == "Tuscaloosa") %>%
  group_by(cityname, state, year) %>%
  summarise(tot_obs = sum(count)) %>%
  view()

# 77 obs
hp_mayors_sub %>%
  mutate(count = 1) %>%
  #filter(year == 2002 | year == 2007) %>%
  filter(city == "Tuscaloosa") %>%
  group_by(city, stateab, year) %>%
  summarise(tot_obs = sum(count)) %>%
  view()


# ISSUE WITH THE JOIN...WHY?

# 14289 obs -> missing 2 obs
full_mayor <- full_join(vogl_mayor_clean, hp_mayors_sub, by = c("cityname" = "city", "state" = "stateab", 
                                                  "year" = "year", "bmayor" = "bmayor", "bever" = "bever"))

# count obs for each city and then compare?

full_mayor %>%
  mutate(count = 1) %>%
  filter(year == 2002 | year == 2007) %>%
  group_by(cityname, state) %>%
  summarise(tot_obs = sum(count)) %>%
  view()

# 628
full_mayor %>%
  filter(year == 2002 | year == 2007)

# 10 
hp_mayors_sub %>%
  mutate(count = 1) %>%
  filter(year == 2002 | year == 2007)

# 618
vogl_mayor_clean %>%
  mutate(count = 1) %>%
  filter(year == 2002 | year == 2007) 

```


```{r population work: fixing missclassifications of survey status, include = FALSE}

# check out Berwyn IL, not recorded as redlined but seems to be in Chicago
# check chicopee and holyoke and whole problematic list
# check montclair NJ

# Newport News is in Mapping Inequality

# take out mismatched classifications 

# take out Barberton, OH - surveyed in MI according to Faber 2020
# take out Duquesne, PA - in MI according to Faber 2020
# take out East Cleveland -> Cleveland was surveyed, also in Mapping Inequality according to Faber 2020
# take out Everett, MA -> in Mapping Inequality according to Faber 2020
# get rid of Ferndale MI -> in Mapping Inequality according to Faber 2020
# Garfield, NJ -> in Mapping Inequality according to Faber 2020
# Hackensack, NJ -> in Mapping Inequality according to Faber 2020
# Homestead, PA -> in Mapping Inequality according to Faber 2020
# Lackawanna NY -> in Mapping Inequality according to Faber 2020
# Middletown, OH -> in Mapping Inequality according to Faber 2020
# New London, CT -> in Mapping Inequality according to Faber 2020
# Newport News, VA -> in Mapping Inequality according to Faber 2020
# Norwalk, CT -> in Mapping Inequality according to Faber 2020
# University City, MO -> in Mapping Inequality according to Faber 2020
# Exclude West NY -> in NJ but right across from Manhattan, graded and within Mapping Inequality, but not Hillier
# Wilkinsburg, PA -> in NJ but right across from Manhattan, graded and within Mapping Inequality, but not Hillier
# Salem, MA -> in Hillier



actually_redlined <- c("Barberton", "Duquesne", "East Cleveland", 
                       "Wilkinsburg", "West New York", "University City",
                       "Norwalk", "Newport News", "New London",
                       "Lackawanna", "Homestead", "Hackensack",
                       "Garfield", "Ferndale") 


cities_1930_20_60_checked <- cities_1930_20_60[!(cities_1930_20_60$cityname == "Salem" & cities_1930_20_60$state == "MA"),]

cities_1930_20_60_checked <- cities_1930_20_60_checked[!(cities_1930_20_60_checked$cityname == "Middletown" & cities_1930_20_60_checked$state == "OH"),]

cities_1930_20_60_checked <- cities_1930_20_60_checked[!(cities_1930_20_60_checked$cityname == "Everett" & cities_1930_20_60_checked$state == "MA"),]

cities_1930_20_60_checked <- cities_1930_20_60_checked %>%
  filter(!(cityname %in% actually_redlined))

# should be 303 - 3 - 14: 286 -> correct!
```


```{r fixing missclassifications of survey status}
# must be own city boundaries or combined pop must be within same range

# not within same city
# in SF

# rules
# no city boundaries but place point -> fine
# no place point -> ok, but can't be within other urban area

not_own_city <- c("Alameda", "Alhambra", "Aliquippa", "Ambridge",
                  "Attleboro", "Bessemer", "Berwyn", "Beverly", "Bloomfield",
                  "Carbondale", "Central Falls", "Chicago Heights",
                  "Cohoes", "Dunmore", "Chelsea", "Chicopee", 
                  "Cleveland Heights", "Clifton", "Council Bluffs",
                  "Cranston", "Dearborn", "East Chicago", "Easton",
                  "Elyria", "Elkhart", "Gloucester", "Granite City",
                  "Hamtramck Village", "Highland Park", "Hoboken", "Holyoke",
                  "Huntington Beach", "Irvington", "Kearny", "Linden",
                  "Lorain", "Malden", "Massillon", "McKeesport",
                  "Medford", "Melrose", "Meriden", "Mishawaka", "Montclair",
                  "Nanticoke", "New Albany", "New Brunswick", "New Rochelle",
                  "Norristown Borough", "Northampton", "Norwich", "Norwood",
                  "Nutley", "Orange", "Peabody", "Perth Amboy", "Plainfield",
                  "Pomona", "Port Chester", "Revere", "Royal Oak", "Salem", 
                  "Santa Ana", "Santa Monica", "Superior", "Union City",
                  "Waltham", "Warren","Washington", "Waukegan", "Wauwatosa",
                  "West Allis", "West Orange", "White Plains", "Woonsocket",
                  "Wyandotte")

length(not_own_city)

cities_1930_20_60_checked <- cities_1930_20_60_checked[!(cities_1930_20_60_checked$cityname == "Belleville" & cities_1930_20_60_checked$state == "IL"),]

cities_1930_20_60_checked <- cities_1930_20_60_checked[!(cities_1930_20_60_checked$cityname == "Belleville" & cities_1930_20_60_checked$state == "NJ"),]

cities_1930_20_60_checked <- cities_1930_20_60_checked[!(cities_1930_20_60_checked$cityname == "Everett" & cities_1930_20_60_checked$state == "WA"),]

cities_1930_20_60_checked <- cities_1930_20_60_checked[!(cities_1930_20_60_checked$cityname == "Kingston" & cities_1930_20_60_checked$state == "PA"),]

cities_1930_20_60_checked <- cities_1930_20_60_checked[!(cities_1930_20_60_checked$cityname == "Middletown" & cities_1930_20_60_checked$state == "CT"),]

cities_1930_20_60_checked <- cities_1930_20_60_checked[!(cities_1930_20_60_checked$cityname == "Portsmouth" & cities_1930_20_60_checked$state == "VA"),]

cities_1930_20_60_checked <- cities_1930_20_60_checked[!(cities_1930_20_60_checked$cityname == "Richmond" & cities_1930_20_60_checked$state == "CA"),]

# combined cities > pop or other city redlined
combined_too_big <- c("Ashland", "Bethlehem", "Fitchburg", "Haverhill", "Leominster",
                      "Lewiston", "Moline", "Riverside", "San Bernardino",
                      "Rock Island", "Saint Petersburg")

cities_1930_20_60_checked <- cities_1930_20_60_checked[!(cities_1930_20_60_checked$cityname == "Alexandria" & cities_1930_20_60_checked$state == "VA"),]

cities_1930_20_60_checked <- cities_1930_20_60_checked[!(cities_1930_20_60_checked$cityname == "Newport" & cities_1930_20_60_checked$state == "KY"),]

cities_1930_20_60_checked <- cities_1930_20_60_checked[!(cities_1930_20_60_checked$cityname == "Rome" & cities_1930_20_60_checked$state == "NY"),]


### GOT THROUGH Cumberland, MD filtered for survey status

cities_1930_20_60_checked <- cities_1930_20_60_checked %>%
  filter(!(cityname %in% not_own_city)) %>%
  filter(!(cityname %in% combined_too_big))


# currently through the Ms

cities_1930_20_60_checked %>%
  filter(cityname == "Wyandotte")


# checking correct # -> good
286 - length(not_own_city) - 7 - length(combined_too_big) - 3

cities_1930_20_60_checked <- cities_1930_20_60_checked %>%
  mutate(cityname = as.character(cityname),
         state = as.character(state))

  
# view(cities_1930_20_60_checked)

cities_1930_20_60_checked %>%
  filter(citypop_total > 30000, citypop_total < 50000, surveyed == 0) %>%
  view()

```

```{r join with mayor data, include = FALSE}

redlined_mayor <- left_join(full_mayor, cities_1930_20_60_checked, by = c("cityname", "state")) %>%
  rename(pop_1930 = citypop_total) 

# cities 30-50
redlined_mayor %>%
  mutate(count = 1) %>%
  filter(!(is.na(surveyed)), pop_1930 >= 30000, pop_1930 <= 50000) %>%
  group_by(cityname, state, surveyed) %>%
  summarise(tot_count = sum(count)) %>%
  view()

# cities 20-60
redlined_mayor %>%
  mutate(count = 1) %>%
  filter(!(is.na(surveyed)),!(is.na(bmayor)), pop_1930 >= 20000, pop_1930 <= 60000) %>%
  group_by(cityname, state, surveyed) %>%
  summarise(tot_count = sum(count)) %>%
  view()

view(redlined_mayor)

redlined_mayor %>%
  filter(cityname == "Lima", state == "OH")

redlined_mayor <- redlined_mayor %>%  
  filter(!(is.na(surveyed))) %>%
  filter(!(is.na(bmayor)))

redlined_mayor %>%
  mutate(count = 1) %>%
  filter(!(is.na(surveyed)), pop_1930 >= 30000, pop_1930 <= 50000) %>%
  group_by(surveyed) %>%
  summarise(tot_count = sum(count))
```

```{r}
vogl_mayor_clean %>%
  filter(cityname == "")

vogl_mayor_clean %>%
  mutate(count = 1) %>%
  group_by(cityname, state) %>%
  summarise(tot_count = sum(count)) %>%
  filter(state == "AL")

vogl_mayor %>%
  mutate(count = 1) %>%
  group_by(city, state) %>%
  summarise(tot_count = sum(count)) %>%
  filter(state == "AL")
```



```{r write data, include = FALSE}
# write csv for all cities mayor and redlining data 

write.csv(redlined_mayor, "redlined_mayor.csv")


redlined_mayor_cities <- redlined_mayor %>%
  mutate(count = 1) %>%
  filter(!(is.na(bmayor))) %>%
  group_by(cityname, state, surveyed) %>%
  summarise(tot = sum(count))

view(redlined_mayor_cities)

unique(redlined_mayor$year)

redlined_mayor %>%
  filter(cityname == "Tuscaloosa")
```

